import { Pool } from 'pg';
import pool from '../config/database.js';
import { User, Address, UserRole } from '../types/index.js';

export class UserModel {
  constructor(public pool: Pool) {}

  async create(
    user: Omit<User, 'id' | 'created_at' | 'role'> & {
      address: Omit<Address, 'id' | 'created_at'>;
      role?: UserRole;
    }
  ): Promise<User> {
    const client = await pool.connect();
    try {
      await client.query('BEGIN');

      let address_id: number | null = null;
      if (user.address) {
        const countryResult = await client.query(
          `WITH inserted AS (
            INSERT INTO countries (name, code) VALUES ($1, $2)
            ON CONFLICT (name) DO NOTHING RETURNING id
          )
          SELECT id FROM inserted UNION SELECT id FROM countries WHERE name = $1`,
          [user.address.country, user.address.country.slice(0, 2).toUpperCase()]
        );
        const country_id = countryResult.rows[0].id;

        const cityResult = await client.query(
          `INSERT INTO cities (name, country_id) VALUES ($1, $2)
           ON CONFLICT (name, country_id) DO NOTHING RETURNING id`,
          [user.address.city, country_id]
        );
        let city_id: number;
        if (cityResult.rows.length > 0) {
          city_id = cityResult.rows[0].id;
        } else {
          const sel = await client.query(
            `SELECT id FROM cities WHERE name = $1 AND country_id = $2`,
            [user.address.city, country_id]
          );
          city_id = sel.rows[0].id;
        }

        const addressResult = await client.query(
          `INSERT INTO addresses (street, city_id, postal_code, geom)
           VALUES ($1, $2, $3, ST_SetSrid(ST_MakePoint($4, $5), 4326)::geography)
           ON CONFLICT (street, city_id, postal_code) DO NOTHING RETURNING id`,
          [
            user.address.street, city_id,
            user.address.postal_code || null,
            user.address.latitude || null,
            user.address.longitude || null,
          ]
        );
        address_id = addressResult.rows[0].id;
      }

      // UUID generated by DB default gen_random_uuid()
      const userResult = await client.query(
        `INSERT INTO users (name, address_id, email, uid, password, phone, description, role, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
         RETURNING id, name, email, uid, phone, description, role, created_at, address_id`,
        [
          user.name, address_id, user.email, user.uid || '',
          user.password, user.phone, user.description,
          user.role || 'renter',
        ]
      );

      await client.query('COMMIT');
      return userResult.rows[0];
    } catch (error:any) {
      await client.query('ROLLBACK');
      if (error.code === '23505') throw new Error('Unique constraint violation: ' + error.detail);
      throw error;
    } finally {
      client.release();
    }
  }

  async findById(id: string, requestedFields: string[] = []): Promise<User | null> {
    const allowed = ['id', 'name', 'email', 'uid', 'phone', 'description', 'role', 'created_at', 'address_id'];
    const userFields = requestedFields.filter(f => !f.startsWith('address.') && f !== 'address').filter(f => allowed.includes(f));
    const includesAddress = requestedFields.includes('address') || requestedFields.some(f => f.startsWith('address.'));

    const query = `
      SELECT ${userFields.length > 0 ? userFields.map(f => `u.${f}`).join(', ') : 'u.id, u.name, u.email, u.uid, u.phone, u.description, u.role, u.created_at, u.address_id'}
      ${includesAddress ? `, COALESCE(json_build_object(
        'id', a.id, 'street', a.street, 'city', c.name, 'country', co.name,
        'postal_code', a.postal_code,
        'latitude', ST_Y(a.geom::geometry), 'longitude', ST_X(a.geom::geometry)
      ), '{}'::json) AS address` : ''}
      FROM users u
      LEFT JOIN addresses a ON u.address_id = a.id
      LEFT JOIN cities c ON a.city_id = c.id
      LEFT JOIN countries co ON c.country_id = co.id
      WHERE u.id = $1
    `;
    const result = await this.pool.query(query, [id]);
    return result.rows[0] || null;
  }

  async findAll(requestedFields: string[] = []): Promise<User[]> {
    const allowed = ['id', 'name', 'email', 'uid', 'phone', 'description', 'role', 'created_at', 'address_id'];
    const userFields = requestedFields.filter(f => !f.startsWith('address.') && f !== 'address').filter(f => allowed.includes(f));
    const includesAddress = requestedFields.includes('address') || requestedFields.some(f => f.startsWith('address.'));

    const query = `
      SELECT ${userFields.length > 0 ? userFields.map(f => `u.${f}`).join(', ') : 'u.id, u.name, u.email, u.uid, u.phone, u.description, u.role, u.created_at, u.address_id'}
      ${includesAddress ? `, COALESCE(json_build_object(
        'id', a.id, 'street', a.street, 'city', c.name, 'country', co.name,
        'postal_code', a.postal_code,
        'latitude', ST_Y(a.geom::geometry), 'longitude', ST_X(a.geom::geometry)
      ), '{}'::json) AS address` : ''}
      FROM users u
      LEFT JOIN addresses a ON u.address_id = a.id
      LEFT JOIN cities c ON a.city_id = c.id
      LEFT JOIN countries co ON c.country_id = co.id
    `;
    const result = await this.pool.query(query);
    return result.rows;
  }

  async update(id: string, user: Partial<User>): Promise<User | null> {
    const fields: string[] = [];
    const values: any[] = [];
    let index = 1;
    for (const [key, value] of Object.entries(user)) {
      if (value !== undefined && key !== 'address' && key !== 'created_at') {
        fields.push(`${key} = $${index++}`);
        values.push(value);
      }
    }
    if (fields.length === 0) return null;
    values.push(id);
    const result = await this.pool.query(
      `UPDATE users SET ${fields.join(', ')} WHERE id = $${index}
       RETURNING id, name, email, uid, phone, description, role, created_at, address_id`,
      values
    );
    return result.rows[0] || null;
  }

  async delete(id: string): Promise<boolean> {
    const result = await this.pool.query(`DELETE FROM users WHERE id = $1`, [id]);
    return (result.rowCount ?? 0) > 0;
  }
}

export default new UserModel(pool);
